<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>[[TEXT_TITLE]]</title>
	[[HTML_HEAD_LINKS]]
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">[[TEXT_OPENNAV]]</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">[[HTML_BODY_NAV_BRAND]]</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          	[[HTML_BODY_NAV_LINKS]]
          </ul>
        </div>
      </div>
    </div>

    <div class="container" id="contents">
    	[[HTML_BODY_CONTENTS]]
    </div>

	[[HTML_BODY_SCRIPTS]]
  </body>
</html>