<div class="company" style="margin-left: [[CONTENTS3]]px; width: [[CONTENTS4]]px; background-color: rgba([[CONTENTS5]],0.5); color: #[[CONTENTS6]];">
	<div class="btn btn-default btn-xs addBrand" style="margin: 5px; float: right;" data-companyid="[[CONTENTS7]]" data-toggle="modal" data-target="#addBrandBox"><i class="glyphicon glyphicon-plus"></i></div>
	<div class="btn btn-warning btn-xs" style="margin: 5px; float: right;"><i class="glyphicon glyphicon-pencil"></i></div>
	[[CONTENTS2]]
	[[CONTENTS1]]
</div>