<div class="btn btn-default" style="position: fixed; right: 5px; top: 55px; z-index: 1020;" data-toggle="modal" data-target="#addCompanyBox"><i class="glyphicon glyphicon-plus"></i></div>
<div id="timeline_ruler" style="width: [[CONTENTS4]]px">
	<div id="timeline_ruler_years">
		[[CONTENTS2]]
	</div>
	<div id="timeline_ruler_marks">
		[[CONTENTS3]]
	</div>
</div>
<div id="timeline" style="width: [[CONTENTS4]]px">
	[[CONTENTS1]]
</div>